# Generated by Django 5.0.2 on 2024-11-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_gender_user_lanaguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='lanaguage',
            field=models.CharField(choices=[('kr', 'Korean'), ('en', 'English')], default='', max_length=2),
        ),
    ]
